version: '3.4'

services:
  bot:
    image: bot:latest
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./files:/app/files"
    build: 
      context: .
      dockerfile: bot.Dockerfile
      tags:
        - "bot:latest"
    restart: always
  downloader:
    image: downloader:latest
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./files:/app/files"
    build: 
      context: .
      dockerfile: downloader.Dockerfile
      tags:
        - "downloader:latest"
    restart: always