# version: '3.9'
services:
  bot:
    image: pvd_bot_image:latest
    env_file:
      - ../.env
    environment:
      - DATABASE_FILE=/db/data.db
      - FILES_PATH=/files
    volumes:
      - "../sources:/app"
      - "../db:/db"
      - "../files:/files"
    command: "python bot.py"
    restart: always
  downloader:
    image: pvd_bot_image:latest
    env_file:
      - ../.env
    environment:
      - DATABASE_FILE=/db/data.db
      - FILES_PATH=/files
    volumes:
      - "../sources:/app"
      - "../db:/db"
      - "../files:/files"
    command: "python downloader.py"
    restart: always

# volumes:
#   sources: "../sources"
#   db: "../db"
#   files: "../files"